create table "public"."cast_search_checkpoint" (
    "id" bigint generated by default as identity not null,
    "timestamp" timestamp with time zone not null default now(),
    "fid" bigint not null
);


alter table "public"."cast_search_checkpoint" enable row level security;

create table "public"."daily_tip_allocation" (
    "allocation_date" date not null,
    "created_at" timestamp with time zone not null default now(),
    "fid" bigint not null,
    "amount" numeric not null,
    "username" text,
    "display_name" text,
    "pfp_url" text,
    "address" text
);


alter table "public"."daily_tip_allocation" enable row level security;

create table "public"."tip" (
    "id" bigint generated by default as identity not null,
    "from_fid" bigint not null,
    "to_fid" bigint not null,
    "amount" numeric not null,
    "allocation_date" date not null,
    "indexed_at" timestamp with time zone not null default now(),
    "casted_at" timestamp with time zone not null,
    "cast_hash" text not null,
    "is_valid" boolean,
    "cast_text" text
);


alter table "public"."tip" enable row level security;

CREATE UNIQUE INDEX cast_search_checkpoint_fid_key ON public.cast_search_checkpoint USING btree (fid);

CREATE UNIQUE INDEX cast_search_checkpoint_pkey ON public.cast_search_checkpoint USING btree (id);

CREATE UNIQUE INDEX daily_tip_allocation_pkey ON public.daily_tip_allocation USING btree (allocation_date, fid);

CREATE INDEX tip_allocation_date_from_fid_amount ON public.tip USING btree (allocation_date DESC, from_fid) INCLUDE (amount);

CREATE INDEX tip_allocation_date_to_fid_amount ON public.tip USING btree (allocation_date DESC, to_fid) INCLUDE (amount);

CREATE INDEX tip_casted_at_desc_from_fid ON public.tip USING btree (casted_at DESC, from_fid);

CREATE UNIQUE INDEX tip_pkey ON public.tip USING btree (id);

alter table "public"."cast_search_checkpoint" add constraint "cast_search_checkpoint_pkey" PRIMARY KEY using index "cast_search_checkpoint_pkey";

alter table "public"."daily_tip_allocation" add constraint "daily_tip_allocation_pkey" PRIMARY KEY using index "daily_tip_allocation_pkey";

alter table "public"."tip" add constraint "tip_pkey" PRIMARY KEY using index "tip_pkey";

alter table "public"."cast_search_checkpoint" add constraint "cast_search_checkpoint_fid_key" UNIQUE using index "cast_search_checkpoint_fid_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.allocation_date_summary(input_date date DEFAULT CURRENT_DATE, input_fid bigint DEFAULT NULL::bigint)
 RETURNS TABLE(fid bigint, allocation_date date, amount_allocated bigint, amount_sent bigint, amount_received bigint, amount_remaining bigint, num_sent bigint, num_received bigint, username text, display_name text, pfp_url text, address text)
 LANGUAGE sql
AS $function$
SELECT
  fid,
  allocation.allocation_date,
  allocation.amount as amount_allocated,
  COALESCE(SUM(sent.amount), 0) as amount_sent,
  COALESCE(SUM(received.amount), 0) as amount_received,
  allocation.amount - COALESCE(SUM(sent.amount), 0) as amount_remaining,
  COALESCE(COUNT(sent.amount), 0) as num_sent,
  COALESCE(COUNT(received.amount), 0) as num_received,
  username,
  display_name,
  pfp_url,
  address
FROM daily_tip_allocation allocation
LEFT JOIN tip sent on sent.from_fid = fid and sent.allocation_date = allocation.allocation_date and sent.is_valid = true
LEFT JOIN tip received on received.to_fid = fid and received.allocation_date = allocation.allocation_date and received.is_valid = true
WHERE allocation.allocation_date = input_date
AND (input_fid is null or allocation.fid = input_fid)
GROUP BY fid, allocation.allocation_date
ORDER BY amount_received desc
$function$
;

create or replace view "public"."distinct_fids" as  SELECT DISTINCT ON (daily_tip_allocation.fid) daily_tip_allocation.fid
   FROM daily_tip_allocation;


CREATE OR REPLACE FUNCTION public.validate_tips()
 RETURNS boolean
 LANGUAGE sql
AS $function$
  WITH validations AS
  (
    SELECT
      *,
      CASE
        WHEN user_allocation_for_day IS NULL THEN NULL
        ELSE user_cummulative_tips_for_day <= user_allocation_for_day
      END AS valid
    FROM (
      SELECT
        *,
        SUM(amount) OVER(PARTITION BY allocation_date, from_fid ORDER BY from_fid, casted_at ASC) user_cummulative_tips_for_day,
        (
          SELECT SUM(daily_tip_allocation.amount)
          FROM daily_tip_allocation
          WHERE daily_tip_allocation.fid = tip.from_fid
          AND daily_tip_allocation.allocation_date = tip.allocation_date
        ) AS user_allocation_for_day
      FROM tip
    ) users
    ORDER BY casted_at ASC
  )
  UPDATE tip tip_row
  SET is_valid = validations.valid
  FROM validations
  WHERE validations.id = tip_row.id;
  SELECT true;
$function$
;

grant delete on table "public"."cast_search_checkpoint" to "anon";

grant insert on table "public"."cast_search_checkpoint" to "anon";

grant references on table "public"."cast_search_checkpoint" to "anon";

grant select on table "public"."cast_search_checkpoint" to "anon";

grant trigger on table "public"."cast_search_checkpoint" to "anon";

grant truncate on table "public"."cast_search_checkpoint" to "anon";

grant update on table "public"."cast_search_checkpoint" to "anon";

grant delete on table "public"."cast_search_checkpoint" to "authenticated";

grant insert on table "public"."cast_search_checkpoint" to "authenticated";

grant references on table "public"."cast_search_checkpoint" to "authenticated";

grant select on table "public"."cast_search_checkpoint" to "authenticated";

grant trigger on table "public"."cast_search_checkpoint" to "authenticated";

grant truncate on table "public"."cast_search_checkpoint" to "authenticated";

grant update on table "public"."cast_search_checkpoint" to "authenticated";

grant delete on table "public"."cast_search_checkpoint" to "service_role";

grant insert on table "public"."cast_search_checkpoint" to "service_role";

grant references on table "public"."cast_search_checkpoint" to "service_role";

grant select on table "public"."cast_search_checkpoint" to "service_role";

grant trigger on table "public"."cast_search_checkpoint" to "service_role";

grant truncate on table "public"."cast_search_checkpoint" to "service_role";

grant update on table "public"."cast_search_checkpoint" to "service_role";

grant delete on table "public"."daily_tip_allocation" to "anon";

grant insert on table "public"."daily_tip_allocation" to "anon";

grant references on table "public"."daily_tip_allocation" to "anon";

grant select on table "public"."daily_tip_allocation" to "anon";

grant trigger on table "public"."daily_tip_allocation" to "anon";

grant truncate on table "public"."daily_tip_allocation" to "anon";

grant update on table "public"."daily_tip_allocation" to "anon";

grant delete on table "public"."daily_tip_allocation" to "authenticated";

grant insert on table "public"."daily_tip_allocation" to "authenticated";

grant references on table "public"."daily_tip_allocation" to "authenticated";

grant select on table "public"."daily_tip_allocation" to "authenticated";

grant trigger on table "public"."daily_tip_allocation" to "authenticated";

grant truncate on table "public"."daily_tip_allocation" to "authenticated";

grant update on table "public"."daily_tip_allocation" to "authenticated";

grant delete on table "public"."daily_tip_allocation" to "service_role";

grant insert on table "public"."daily_tip_allocation" to "service_role";

grant references on table "public"."daily_tip_allocation" to "service_role";

grant select on table "public"."daily_tip_allocation" to "service_role";

grant trigger on table "public"."daily_tip_allocation" to "service_role";

grant truncate on table "public"."daily_tip_allocation" to "service_role";

grant update on table "public"."daily_tip_allocation" to "service_role";

grant delete on table "public"."tip" to "anon";

grant insert on table "public"."tip" to "anon";

grant references on table "public"."tip" to "anon";

grant select on table "public"."tip" to "anon";

grant trigger on table "public"."tip" to "anon";

grant truncate on table "public"."tip" to "anon";

grant update on table "public"."tip" to "anon";

grant delete on table "public"."tip" to "authenticated";

grant insert on table "public"."tip" to "authenticated";

grant references on table "public"."tip" to "authenticated";

grant select on table "public"."tip" to "authenticated";

grant trigger on table "public"."tip" to "authenticated";

grant truncate on table "public"."tip" to "authenticated";

grant update on table "public"."tip" to "authenticated";

grant delete on table "public"."tip" to "service_role";

grant insert on table "public"."tip" to "service_role";

grant references on table "public"."tip" to "service_role";

grant select on table "public"."tip" to "service_role";

grant trigger on table "public"."tip" to "service_role";

grant truncate on table "public"."tip" to "service_role";

grant update on table "public"."tip" to "service_role";


